const imagePath = "pictures/";

const hotelDatabase = [
    {
        id: 1,
        name: "Boracay Beach Resort",
        location: "Boracay, Aklan",
        price: 4500,
        category: "beach",
        image: imagePath + "boracay.jpg",
        subImages: [imagePath + "Boracay Beach Resort(1).jpg", imagePath + "Boracay Beach Resort(2).jpg"],
        rating: 5,
        coordinates: [11.9674, 121.9248],
        description: "A stunning beachfront escape offering crystal clear waters and white sand.",
        amenities: ["Free WiFi", "Swimming Pool", "Beach Access", "Restaurant", "Spa"],
        reviews: []
    },
    {
        id: 2,
        name: "The Manila Hotel",
        location: "One Rizal Park, Manila",
        price: 3200,
        category: "city",
        image: imagePath + "manila.jpg",
        subImages: [imagePath + "Manila City Hotel.jpg", imagePath + "Manila City Hotel (2).jpg"],
        rating: 5,
        coordinates: [14.5895, 120.9751],
        description: "Overlooking the South Harbor, this iconic luxury hotel is a refined sanctuary.",
        amenities: ["Free WiFi", "Fitness Center", "Restaurant", "Bar", "Conference Rooms"],
        reviews: []
    },
    {
        id: 3,
        name: "Baguio Mountain Lodge",
        location: "Baguio City",
        price: 5800,
        category: "mountain",
        image: imagePath + "baguio.jpg",
        subImages: [imagePath + "Baguio Mountain(1).jpg", imagePath + "Baguio Mountain Lodge(2).jpg"],
        rating: 4,
        coordinates: [16.4023, 120.5960],
        description: "Nestled in the cold mountains of Baguio with a cozy stone fireplace.",
        amenities: ["Free WiFi", "Fireplace", "Mountain View", "Restaurant", "Parking"],
        reviews: []
    },
    {
        id: 4,
        name: "Cebu Bay Hotel",
        location: "Cebu City",
        price: 3800,
        category: "city",
        image: imagePath + "cebu.jpg",
        subImages: [imagePath + "Cebu Bay Hotel(1).jpg", imagePath + "Cebu Bay Hotel(2).jpg"],
        rating: 4,
        coordinates: [10.3157, 123.8854],
        description: "Featuring a stunning rooftop infinity pool overlooking the city skyline.",
        amenities: ["Free WiFi", "Infinity Pool", "Rooftop Bar", "Gym", "Restaurant"],
        reviews: []
    },
    {
        id: 5,
        name: "El Nido Island Resort",
        location: "Palawan",
        price: 7200,
        category: "beach",
        image: imagePath + "El Nido Island Resort.jpg",
        subImages: [imagePath + "El Nido Island Resort(2).jpg", imagePath + "El Nido Island Resort (3).jpg"],
        rating: 5,
        coordinates: [11.1955, 119.4140],
        description: "A paradise tucked away in limestone cliffs with private villas.",
        amenities: ["Private Beach", "Water Sports", "Spa", "Fine Dining", "Diving Center"],
        reviews: []
    },
    {
        id: 6,
        name: "Davao Downtown Inn",
        location: "Davao City",
        price: 2300,
        category: "city",
        image: imagePath + "Davao Downtown Inn.jpg",
        subImages: [imagePath + "Davao Downtown Inn - Hop Inn Hotel Davao(1).jpg", imagePath + "Davao Downtown Inn - Hop Inn Hotel Davao(2).jpg"],
        rating: 3,
        coordinates: [7.0707, 125.6092],
        description: "Modern, clean, and perfect for business travelers in downtown Davao.",
        amenities: ["Free WiFi", "24/7 Reception", "Business Center", "Breakfast"],
        reviews: []
    },
    {
        id: 7,
        name: "Siargao Surfers Retreat",
        location: "General Luna, Siargao",
        price: 3500,
        category: "beach",
        image: imagePath + "Siargao Surfers Retreat.jpg",
        subImages: [imagePath + "Siargao Surfers Retreat(2).jpg", imagePath + "Siargao Surfers Retreat(3).jpg"],
        rating: 5,
        coordinates: [9.7915, 126.1610],
        description: "The ultimate destination for surfers and island lovers, located near Cloud 9.",
        amenities: ["Surfboard Rental", "Beach Access", "Restaurant", "Bar", "Yoga Classes"],
        reviews: []
    },
    {
        id: 8,
        name: "Bohol Panglao Resort",
        location: "Panglao, Bohol",
        price: 5500,
        category: "beach",
        image: imagePath + "Bohol Panglao Resort.jpg",
        subImages: [imagePath + "Bohol Panglao Resort(2).jpg", imagePath + "Bohol Panglao Resort(3).jpg"],
        rating: 4,
        coordinates: [9.5552, 123.7744],
        description: "Tropical luxury near the famous white sands of Alona Beach and the Chocolate Hills.",
        amenities: ["Beach Access", "Swimming Pool", "Spa", "Restaurant", "Tour Desk"],
        reviews: []
    },
    {
        id: 9,
        name: "Tagaytay Ridge View",
        location: "Tagaytay City",
        price: 4200,
        category: "mountain",
        image: imagePath + "Tagaytay Ridge View.jpg",
        subImages: [imagePath + "Tagaytay Ridge View(2).jpg", imagePath + "Tagaytay Ridge View(3).jpg"],
        rating: 5,
        coordinates: [14.1153, 120.9621],
        description: "Enjoy the cool breeze and the iconic view of Taal Volcano from your balcony.",
        amenities: ["Volcano View", "Restaurant", "Garden", "Parking", "Free WiFi"],
        reviews: []
    },
    {
        id: 10,
        name: "Vigan Heritage Mansion",
        location: "Vigan City, Ilocos Sur",
        price: 2800,
        category: "city",
        image: imagePath + "Vigan Heritage Mansion.jpg",
        subImages: [imagePath + "Vigan Heritage Mansion(2).jpg", imagePath + "Vigan Heritage Mansion(3).jpg"],
        rating: 4,
        coordinates: [17.5747, 120.3875],
        description: "Experience the charm of the Spanish colonial era in this beautifully preserved mansion.",
        amenities: ["Historic Building", "Restaurant", "Cultural Tours", "Free WiFi", "Parking"],
        reviews: []
    }
];
